### PR TITLE
Add subsquid

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR adds Subsquid to the Indexers section

Things left to do:
- [x] Get .svg for index page icon
- [ ] ~~Update terminal images to be larger & with Moonbeam colors~~
- [x] Add instructions for Moonbeam & Moonbase Alpha (if this is supported, not sure)
- [ ] ~~Potentially add info on how to launch an archive instead of using pre-deployed ones~~

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

### CODE REVIEW

**Comment by eshaben** [comment]
@RaekwonIII thanks. So I followed the steps on how to launch an EVM compatible archive by modifying the `docker-compose.yml` and added the Moonbase Alpha WSS endpoint. How do I know that worked? And how do I access my local archive in the processor file? I wouldn't use `lookupArchive` because Moonbase Alpha isn't in the registry, right?

**Comment by RaekwonIII** [comment]
I apologize for the delay @eshaben , those are valid questions I honestly didn't think of 😅 
I'm going to integrate answers to the branch shortly.

**Comment by eshaben** [comment]
No worries @RaekwonIII, thanks for updating the docs, that definitely helps.

I'm just personally trying to run Moonbase Alpha so I can know how it all works and ties together, but I have yet to be successful. Do I need to update something if I am a macos user? I can't seem to get a local archive running on macos. I don't have an M1, but do I still need to follow those instructions here: https://docs.subsquid.io/recipes/how-to-launch-a-squid-archive#caveats-for-m1-macs? 

I have a VPS server running ubuntu and I'm at least able to go to localhost:4010 and see the console now. So I guess for local archive nodes, you only have to run `docker-compose up -d` and then do I need to run the following snippets (https://github.com/PureStake/moonbeam-docs/pull/291/files#diff-15b967d207634b4ad655226ebb99e48248bb5da758de66e31458245ab39e8c24R484-R532)? Anytime I try I get the following error: 

```
Error: connect ECONNREFUSED 127.0.0.1:23798
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 23798
}
```

I don't know if thats related to using my VPS or what haha... I'm sorry for all the confusion but I can't get anything to work 😅 

I'm trying to modify the template and add a `docker-compose.yml` file for Moonbase Alpha. I took the Moonbeam one from the archive repo (https://github.com/subsquid/squid-archive-setup/blob/main/moonbeam/docker-compose.yml) and modified the wss url and just used that.

**Comment by RaekwonIII** [comment]
> No worries @RaekwonIII, thanks for updating the docs, that definitely helps.
> 
> I'm just personally trying to run Moonbase Alpha so I can know how it all works and ties together, but I have yet to be successful. Do I need to update something if I am a macos user? I can't seem to get a local archive running on macos. I don't have an M1, but do I still need to follow those instructions here: https://docs.subsquid.io/recipes/how-to-launch-a-squid-archive#caveats-for-m1-macs?
> 
> On macos, this is the only docker container that spins up: Screen Shot 2022-04-18 at 11 35 43 PM
> 

Hey @eshaben thanks for sticking with it! 😅 
Let me try and help as best as I can: so, about the MacOS issue: that is specific to M1 chips, it should not concern you.

As I look at your screenshot, though, I think there is some confusion: that container is related to the project discussed in the guide itself: the `squid-template` comes with a `docker-compose.yml` that describes a PostgreSQL service. This is necessary to store the processed chain data and used by the GraphQL server as the data source for the API.

The `docker-compose.yml` file for the Archive is a completely different matter, my advice is to save it and launch it from a different folder, so it's less confusing.

> I have a VPS server running ubuntu and I'm at least able to go to localhost:4010 and see the console now. So I guess for local archive nodes, you only have to run `docker-compose up -d` and then do I need to run the following snippets (https://github.com/PureStake/moonbeam-docs/pull/291/files#diff-15b967d207634b4ad655226ebb99e48248bb5da758de66e31458245ab39e8c24R484-R532)? 

Can you please help me understand a bit more, there's a couple of things I'm not getting from this sentence:

1. Are you able to connect to the VPS via `localhost`? Does it not have a URL or IP you can use to reach it from anywhere?
2. When I click on the link, it does not show me a particular file or section with a snippet, so I am not sure what snippets you are pointing at.

In any case, I'm going to try and answer that: you are correct on the assumption that, if everything is setup with the Archive docker file, you just need to run `docker-compose up -d` and it will start extracting data from the chain. Launching the console on the browser is just a test to see if everything is OK.

> Anytime I try I get the following error:
> 
> ```
> Error: connect ECONNREFUSED 127.0.0.1:23798
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 23798
> }
> ```
> 
> I don't know if thats related to using my VPS or what haha... I'm sorry for all the confusion but I can't get anything to work 😅
> 

From the looks of it, it seems like it's trying to connect to port 23798, instead of 4010 for some reasons.

But there are a couple of things I am not sure I understand here: when that error pops up (what command did you launch, ...) and how you are trying to connect to the VPS, versus how you are supposed to connect to it.

In the guide for [setting up an Archive](https://docs.subsquid.io/recipes/how-to-launch-a-squid-archive#use-local-archive-in-a-squid-api), we specify that `http://localhost:4010/v1/graphql` is the URL that should be used when setting up the processor, but that is true if the Archive is launched locally and can be reached via `localhost` connection.

> I'm trying to modify the template and add a `docker-compose.yml` file for Moonbase Alpha. I took the Moonbeam one from the archive repo (https://github.com/subsquid/squid-archive-setup/blob/main/moonbeam/docker-compose.yml) and modified the wss url and just used that.

This is indeed the correct procedure. To clarify it:

1. in an arbitrary folder (different from the Squid project's folder), containing the `docker-compose.yml` for the Archive, run the command to launch it (`docker compose up -d)
image
2. in the Squid project folder, launch the Postgresql service via the same command (although launching a different `docker-compose.yml` configuration file)
image
3. (if migrations are done, models are generated, wrappers are generated, code has been built) run the processor:
image
(`make process` is just an alias for `node -r dotenv/config lib/processor.js` defined in the `Makefile`)

and for full transparency, this is how I changed my `processor.ts` in order to connect to my **local** Archive:

```typescript
processor.setDataSource({
  chain: CHAIN_NODE,
  archive: "http://localhost:4010/v1/graphql",
  // archive: lookupArchive("moonriver")[0].url,
});
```

**Comment by RaekwonIII** [comment]
Leaving a second reply, because I have been told we have deployed a **Moonbase** Archive and released the `0.0.6` version of our `archive-registry` npm package which makes it available for lookup.

Using this to configure the processor worked well for me:

```typescript
processor.setDataSource({
  chain: "wss://wss.api.moonbase.moonbeam.network",
  // archive: "http://localhost:4010/v1/graphql",
  archive: lookupArchive("moonbase")[0].url,
});
```

By the way, sorry if this is a noob question, why is Moonbeam documentation reporting a different WSS endpoint?
https://docs.moonbeam.network/builders/get-started/endpoints/#relay-chain
What's the difference? Are there two different "Moonbase" chains?

**Comment by eshaben** [comment]
Thanks for all of the help @RaekwonIII ! 🙌 

This all makes sense now. I see what I was doing wrong. I was really trying to make minimal changes to get the local archive node spun up so that in the documentation I wouldn't have to include a bunch of additional steps that only applied to Moonbase Alpha. I really just didn't want to confuse users. But with that being said, the release of the Moonbase Alpha archive addresses any concerns with that matter and I was able to make the two small changes to get it to work there, so that's awesome! I appreciate all of your help! 🙂 

I'll try and get the docs wrapped up and merged this week! 🚀 

> By the way, sorry if this is a noob question, why is Moonbeam documentation reporting a different WSS endpoint?
https://docs.moonbeam.network/builders/get-started/endpoints/#relay-chain
What's the difference? Are there two different "Moonbase" chains?

We run our own relay chain for Moonbase Alpha instead of using Westend. So if you wanted to connect to the relay chain, you could use the WSS endpoint from that link. Otherwise to interact with Moonbase Alpha itself, you would just use this one `wss://wss.api.moonbase.moonbeam.network`... so there is really only one Moonbase Alpha chain

**Comment by eshaben** [comment]
@RaekwonIII I don't think there is anything that really needs to be improved on your end. My issue was that I was trying to modify the existing template's `docker-compose.yml` instead of running the archive node in a separate directory. I was trying to simplify the process for the sake of the tutorial. I think if you're running an archive node realistically keeping it separate makes sense.

**Comment by eshaben** [comment]
@albertov19 this is ready for a final review 🚀

**Review by albertov19 — APPROVED** [review]
LGTM, If this can be shortened it would be ideal (not mandatory). Also, make sure you mark off all the items needed in the checklist.

**Pull request merged**
