### PR TITLE
Add Bobabeam Docs

### PR DESCRIPTION
**Pull request by themacexpert**
### Description

This PR adds a Getting Started page for the Bobabeam network and updates the Bobabase page with information on changing your gas fee token. There were also a number of image and logo changes. **_Compress_Images.py_** was run but did not detect any image compression required. 

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

### CODE REVIEW

**Review by eshaben — COMMENTED** [review]
This looks good!! Only one question, do you think there is anything we can do to change the icon for one or the other here, it just looks a little bit strange using the same one but also I have no idea what we could do about it 

Screen Shot 2022-08-24 at 12 23 29 PM

**Comment by albertov19** [comment]
> This looks good!! Only one question, do you think there is anything we can do to change the icon for one or the other here, it just looks a little bit strange using the same one but also I have no idea what we could do about it
> 
> Screen Shot 2022-08-24 at 12 23 29 PM

We could add the Moonbeam and Moonbase logo in the top right corner or something?

**Comment by themacexpert** [comment]
@albertov19 @eshaben new proposed logos:
Screen Shot 2022-08-24 at 10 00 51 AM

**Review by eshaben — APPROVED** [review]
LGTM! Thanks!! ✨ 🚀

**Pull request merged**
