### PR TITLE
DRAFT PR - adding docs for parachain 

### PR DESCRIPTION
**Pull request by artkaseman**
DRAFT

### CODE REVIEW

**Comment by artkaseman** [comment]
> > You need a spec file to run the parachain
> 
> FYI, This will change soon. We will start baking the specs of public networks into the node binary. Then node operators will not need to obtain a separate spec file.

Will this be in v5?

**Comment by crystalin** [comment]
I think we can have it in v5 yes (@Jsohy)

Le mer. 6 janv. 2021 à 10:40, Art Kaseman <notifications@github.com> a
écrit :

**Comment by purestaketdb** [comment]
Needs some brief explanation about the relay chain being ours for Alphanet and Kusama for Moonriver and Polkadot for Moonbeam in the top/preamble.

**Comment by artkaseman** [comment]
new draft up

**Pull request closed without merging**
